@echo off
REM ===================================================================
REM  EvidenceCompare AI - LIVE launcher (Windows)
REM  Runs the app in LIVE mode: reports are generated by Claude from
REM  current literature retrieved from PubMed/EuropePMC/etc.
REM
REM  BEFORE using this: create apps\api\.env with your keys, e.g.
REM     ANTHROPIC_API_KEY=sk-ant-...      (required for live AI)
REM     VOYAGE_API_KEY=pa-...             (optional; better embeddings)
REM     NCBI_API_KEY=...                  (optional; higher PubMed limits)
REM     NCBI_EMAIL=you@example.com
REM  With no ANTHROPIC_API_KEY, "auto" mode safely falls back to offline.
REM ===================================================================
setlocal
set "ROOT=%~dp0"

echo.
echo   Starting EvidenceCompare AI in LIVE mode...
echo   (reports will use Claude + live evidence when keys are present)
echo.

REM --- Free the ports first so a re-launch is always clean
for /f "tokens=5" %%p in ('netstat -ano ^| findstr ":8000" ^| findstr LISTENING') do taskkill /PID %%p /F >nul 2>&1
for /f "tokens=5" %%p in ('netstat -ano ^| findstr ":3000" ^| findstr LISTENING') do taskkill /PID %%p /F >nul 2>&1

REM --- Backend (FastAPI) in auto mode; keys come from apps\api\.env
start "EvidenceCompare API (LIVE)" /D "%ROOT%apps\api" cmd /k "set EVIDENCE_MODE=auto&& set LLM_MODE=auto&& .venv\Scripts\python.exe -m uvicorn app.main:app --port 8000"

REM --- Frontend (Next.js) on http://localhost:3000
start "EvidenceCompare Web" /D "%ROOT%apps\web" cmd /k "npm run dev"

echo   Waiting for the servers to warm up...
timeout /t 15 /nobreak >nul

echo   Opening http://localhost:3000 in your browser...
start "" http://localhost:3000

echo.
echo   ------------------------------------------------------------
echo   EvidenceCompare AI is running in LIVE mode.
echo     Web app : http://localhost:3000
echo     API     : http://localhost:8000/docs
echo     Check   : http://localhost:8000/health  (see "modes" -> llm_live_ready)
echo.
echo   To STOP: close the two server windows (or run stop-app.bat).
echo   ------------------------------------------------------------
echo.
echo   You can close THIS window now.
timeout /t 8 >nul
