"""initial schema

Baseline for EvidenceCompare AI: users, molecules, reports and all report
children (sections, comparison_rows w/ rationale, citations w/ study_design,
evidence_docs, doc_chunks, agent_runs, exports) plus reports.molecule_evidence.

`doc_chunks.embedding` is JSON for cross-database portability. In production a
follow-up migration swaps it for a pgvector `vector(1024)` column + HNSW index
(the compose db image already ships pgvector).

Revision ID: 1e97fd1330a4
Revises:
Create Date: 2026-07-04 01:55:49.793470
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e97fd1330a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_docs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('pmid', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('study_design', sa.String(length=48), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_docs_doi'), 'evidence_docs', ['doi'], unique=False)
    op.create_index(op.f('ix_evidence_docs_pmid'), 'evidence_docs', ['pmid'], unique=False)
    op.create_table('molecules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rxnorm_id', sa.String(length=64), nullable=True),
    sa.Column('atc_code', sa.String(length=16), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_molecules_name'), 'molecules', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('molecule_a', sa.String(length=255), nullable=False),
    sa.Column('molecule_b', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('model_synthesis', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('source_snapshot', sa.JSON(), nullable=True),
    sa.Column('molecule_evidence', sa.JSON(), nullable=True),
    sa.Column('token_cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_share_token'), 'reports', ['share_token'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_report_id'), 'agent_runs', ['report_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('doc_id', sa.Uuid(), nullable=True),
    sa.Column('ref_key', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('study_design', sa.String(length=48), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('pmid', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('locator', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['evidence_docs.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_report_id'), 'citations', ['report_id'], unique=False)
    op.create_table('comparison_rows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('attribute', sa.String(length=255), nullable=False),
    sa.Column('value_a', sa.Text(), nullable=False),
    sa.Column('value_b', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('citation_ids', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_rows_report_id'), 'comparison_rows', ['report_id'], unique=False)
    op.create_table('doc_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doc_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['evidence_docs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_chunks_doc_id'), 'doc_chunks', ['doc_id'], unique=False)
    op.create_index(op.f('ix_doc_chunks_report_id'), 'doc_chunks', ['report_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('object_url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_report_id'), 'exports', ['report_id'], unique=False)
    op.create_table('report_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('section_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('insufficient_evidence', sa.Boolean(), nullable=False),
    sa.Column('claims', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_sections_report_id'), 'report_sections', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_sections_report_id'), table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index(op.f('ix_exports_report_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_doc_chunks_report_id'), table_name='doc_chunks')
    op.drop_index(op.f('ix_doc_chunks_doc_id'), table_name='doc_chunks')
    op.drop_table('doc_chunks')
    op.drop_index(op.f('ix_comparison_rows_report_id'), table_name='comparison_rows')
    op.drop_table('comparison_rows')
    op.drop_index(op.f('ix_citations_report_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_agent_runs_report_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_share_token'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_molecules_name'), table_name='molecules')
    op.drop_table('molecules')
    op.drop_index(op.f('ix_evidence_docs_pmid'), table_name='evidence_docs')
    op.drop_index(op.f('ix_evidence_docs_doi'), table_name='evidence_docs')
    op.drop_table('evidence_docs')
    # ### end Alembic commands ###
